version: "3.9"
services:
  mysql:
    image: mysql:8.3
    ports:
      - "33007:3306"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: kien0901
      MYSQL_DATABASE: 2ndbrand
      MYSQL_ROOT_HOST: "%"
      # MYSQL_USER: kiennd
      # MYSQL_PASSWORD: kien0901
    volumes:
      - ./_database/volume/mysql:/var/lib/mysql
      - ./_database/query:/docker-entrypoint-initdb.d/
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    restart: always
  rabbitmq:
    image: "rabbitmq:3.12-management"
    ports:
      - "5672:5672" # AMQP port
      - "15672:15672" # RabbitMQ management plugin port
    # environment:
    #   RABBITMQ_DEFAULT_USER: "admin"
    #   RABBITMQ_DEFAULT_PASS: "admin"
  elasticsearch:
    image: elasticsearch:8.13.4
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - ./_database/volume/elasticsearch:/usr/share/elasticsearch/data
    environment:
      - discovery.type=single-node
    # restart: always
  kibana:
    image: kibana:8.13.4
    ports:
      - "5601:5601"
    restart: always
    depends_on:
      - elasticsearch
    # ulimits:
    #   memlock:
    #     soft: -1
    #     hard: -1
    # mem_limit: 2g
    # cap_add:
    #   - IPC_LOCK
    # healthcheck:
    #   test: ["CMD-SHELL", "curl --write-out 'HTTP %{http_code}' --fail --silent --output /dev/null http://localhost:9200/"]
    #   interval: 30s
    #   timeout: 30s
    #   retries: 3
