app:
  port: "8087" # port of the app
  gin_mode: "debug" # "release" , "debug"
  secret_key: "zxcvbnm123qwertyui0987fghj5678lk"
clickhouse:
  hostname: "192.168.90.8"
  port: 32511
  username: "admin"
  password: "123465"
  name: "gapone"
mysql:
  hostname: 127.0.0.1
  port: 33007
  username: "root"
  password: "kien0901"
  name: "gapone"
sms:
  api_key: "your_api_key"
  username: "your_username"
  password: "your_password"
redis:
  hostname: "localhost"
  port: "6379"
rabbitmq:
  hostname: "localhost"
  port: "5672"
  username: "guest"
  password: "guest"
